import type { Metadata } from "next";
import { Montserrat, PlayfairDisplay } from "@/lib/font";
import "./globals.css";
import clsxm from "@/lib/clsxm";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsxm(Montserrat.variable, PlayfairDisplay.variable)}>
        {children}
      </body>
    </html>
  );
}
